### ISSUE TITLE
collection_select filtering

### ISSUE THREAD

**Issue by CollinSchneider** [CollinSchneider/Tabled#2]
Trying to only show tables in my dropdown where the status = 0 and the capacity < party capacity, but can't get to filter at all.
Tried:
Parties Controller:
    @tables = Table.where(:status == 0)

in my party show view:
   <%= form_for @party do |f| %>
    <%= f.label "Seat Party at Table:" %>
    <%= f.collection_select :table_id, @tables, :id, :table_num, include_blank: false %>
    <%= f.hidden_field :status, value: 1 %>
  <%= f.submit "Seat Party"%>
  <% end %>

**Comment by ajhofferber** [comment]
Hey Collin,  

instead of:
```@tables = Table.where(:status == 0)```

Try something like:
```@tables = Table.where('status = ?', 0)```

**Comment by ajhofferber** [comment]
Let me know if that helps at all, and if not, we can pair for a few minutes when we finish our instructor meeting.
